import type { Product } from "@/lib/types";

const SIZES = ["XS", "S", "M", "L", "XL", "XXL"];
const COLORS_RUNNING = ["Black", "Navy", "Red"];
const COLORS_TRAINING = ["Black", "Charcoal", "Forest"];
const COLORS_BASIC = ["Black", "White", "Gray"];

function makeVariants(sizes: string[], colors: string[]) {
  return sizes.flatMap((size) =>
    colors.map((color) => ({ size, color, stock: Math.floor(Math.random() * 20) + 2 }))
  );
}

export const products: Product[] = [
  {
    id: "champion-running-tee",
    name: "Champion Running Tee",
    category: "Running",
    price: 68,
    compareAtPrice: 89,
    availability: "In stock",
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800&h=800&fit=crop",
    ],
    description: "Lightweight, moisture-wicking shirt engineered for high-performance running. Features advanced ventilation panels and premium DryTech fabric technology that keeps you cool and dry mile after mile.",
    features: ["Moisture-wicking DryTech fabric", "4-way stretch construction", "Anti-chafe flatlock seams", "UPF 40+ UV protection", "Reflective details for low-light visibility"],
    variants: makeVariants(SIZES, COLORS_RUNNING),
    reviews: [
      { id: "r1", author: "Marcus T.", rating: 5, date: "2024-11-15", title: "Best running tee I've owned", body: "Wore this for my marathon and stayed completely dry. The fit is perfect and doesn't ride up.", verified: true },
      { id: "r2", author: "Sarah K.", rating: 4, date: "2024-10-22", title: "Great quality", body: "Very comfortable and breathable. Sizing runs a little large, so size down if between sizes.", verified: true },
      { id: "r3", author: "James L.", rating: 5, date: "2024-09-08", title: "Worth every penny", body: "This shirt has survived 6 months of daily training and still looks brand new.", verified: false },
    ],
    rating: 4.7,
    reviewCount: 128,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    brand: "Nike",
    sku: "GMG-RT-001",
    tags: ["running", "performance", "tops"],
  },
  {
    id: "elite-training-shorts",
    name: "Elite Training Shorts",
    category: "Training",
    price: 78,
    availability: "In stock",
    imageUrl: "https://images.unsplash.com/photo-1506629082847-11d82e59545e?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1506629082847-11d82e59545e?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=800&fit=crop",
    ],
    description: "Engineered for intense workouts. Built with premium compression technology and performance materials designed for maximum range of motion.",
    features: ["Dual-layer compression liner", "4 zip-close pockets", "Breathable mesh side panels", "Sweat-resistant waistband", "7-inch inseam for full mobility"],
    variants: makeVariants(["S", "M", "L", "XL", "XXL"], COLORS_TRAINING),
    reviews: [
      { id: "r4", author: "Alex P.", rating: 5, date: "2024-11-01", title: "Game changer for leg day", body: "These shorts are incredibly comfortable and the pockets actually hold my phone securely.", verified: true },
      { id: "r5", author: "Donna M.", rating: 4, date: "2024-10-12", title: "Great shorts", body: "Excellent compression and the fabric is top quality.", verified: true },
    ],
    rating: 4.5,
    reviewCount: 89,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    brand: "Adidas",
    sku: "GMG-TS-002",
    tags: ["training", "shorts", "compression"],
  },
  {
    id: "performance-jacket",
    name: "Performance Running Jacket",
    category: "Running",
    price: 158,
    compareAtPrice: 199,
    availability: "In stock",
    imageUrl: "https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop",
    ],
    description: "Premium all-weather athletic jacket engineered for peak performance in any condition. Combines waterproof protection with advanced breathability technology.",
    features: ["DWR waterproof coating", "360° reflective print", "Tapered athletic fit", "Underarm ventilation zip", "Packable into chest pocket"],
    variants: makeVariants(SIZES, COLORS_RUNNING),
    reviews: [
      { id: "r6", author: "Tom B.", rating: 5, date: "2024-11-20", title: "Perfect for all weather training", body: "Wore this in heavy rain for a 10-mile run and stayed completely dry.", verified: true },
    ],
    rating: 4.8,
    reviewCount: 64,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    brand: "Nike",
    sku: "GMG-RJ-003",
    tags: ["running", "jacket", "weather-resistant"],
  },
  {
    id: "lifestyle-tank",
    name: "Essential Tank Top",
    category: "Lifestyle",
    price: 52,
    availability: "In stock",
    imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1505521585350-967ad8b73293?w=800&h=800&fit=crop",
    ],
    description: "Versatile performance tank top for any athletic activity. Minimalist design meets maximum comfort.",
    features: ["Seamless construction", "Ultra-breathable mesh fabric", "Relaxed athletic fit", "Tagless design", "Machine washable"],
    variants: makeVariants(SIZES, COLORS_BASIC),
    reviews: [
      { id: "r7", author: "Casey R.", rating: 5, date: "2024-10-30", title: "My go-to gym tank", body: "Incredibly soft and the fit is perfect. I own 4 of these now.", verified: true },
    ],
    rating: 4.4,
    reviewCount: 203,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    brand: "Puma",
    sku: "GMG-ET-004",
    tags: ["lifestyle", "tank", "tops"],
  },
  {
    id: "pro-compression-leggings",
    name: "Pro Compression Leggings",
    category: "Training",
    price: 128,
    compareAtPrice: 159,
    availability: "In stock",
    imageUrl: "https://images.unsplash.com/photo-1506629082847-11d82e59545e?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1506629082847-11d82e59545e?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=800&fit=crop",
    ],
    description: "Advanced compression technology designed for serious athletes. Engineered to support muscle recovery during and after performance.",
    features: ["Graduated compression technology", "Dual thigh pockets", "High-rise flexible waistband", "Squat-proof fabric", "Recovery performance technology"],
    variants: makeVariants(["XS", "S", "M", "L", "XL"], ["Black", "Midnight", "Forest"]),
    reviews: [
      { id: "r9", author: "Rachel M.", rating: 5, date: "2024-11-05", title: "Best leggings for heavy lifting", body: "Squat-proof, stays in place, and incredibly flattering. Worth every penny.", verified: true },
    ],
    rating: 4.9,
    reviewCount: 312,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    brand: "Under Armour",
    sku: "GMG-CL-005",
    tags: ["training", "leggings", "compression"],
  },
  {
    id: "marathon-socks",
    name: "Marathon Performance Socks",
    category: "Accessories",
    price: 24,
    availability: "In stock",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop",
    ],
    description: "Premium performance socks engineered for long-distance running. Superior cushioning and moisture management.",
    features: ["Targeted arch support", "Moisture-wicking merino blend", "Anti-blister padding", "Reinforced heel and toe", "No-slip cuff"],
    variants: [
      { size: "S (US 5-7)", color: "White", stock: 15 },
      { size: "M (US 8-10)", color: "White", stock: 22 },
      { size: "L (US 11-13)", color: "White", stock: 10 },
      { size: "S (US 5-7)", color: "Black", stock: 18 },
      { size: "M (US 8-10)", color: "Black", stock: 30 },
      { size: "L (US 11-13)", color: "Black", stock: 12 },
    ],
    reviews: [
      { id: "r10", author: "Paul S.", rating: 5, date: "2024-10-18", title: "Zero blisters in 26.2 miles", body: "These socks got me through my first marathon without a single blister.", verified: true },
    ],
    rating: 4.6,
    reviewCount: 445,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    brand: "Asics",
    sku: "GMG-MS-006",
    tags: ["accessories", "socks", "running"],
  },
  {
    id: "champion-hoodie",
    name: "Champion Training Hoodie",
    category: "Training",
    price: 98,
    availability: "In stock",
    imageUrl: "https://images.unsplash.com/photo-1556821552-5f6b9ce1d9af?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1556821552-5f6b9ce1d9af?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop",
    ],
    description: "The ultimate warm-up companion. Crafted from a premium cotton-poly blend with fleece lining for warmth without the bulk.",
    features: ["Premium cotton-poly fleece blend", "Kangaroo pocket", "Thumb holes for arm coverage", "Tapered athletic cut", "Adjustable hood drawcord"],
    variants: makeVariants(SIZES, COLORS_TRAINING),
    reviews: [
      { id: "r12", author: "Kevin D.", rating: 5, date: "2024-11-12", title: "Perfect warm-up hoodie", body: "Incredibly soft inside and the fit is great.", verified: true },
    ],
    rating: 4.7,
    reviewCount: 178,
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    brand: "New Balance",
    sku: "GMG-CH-007",
    tags: ["training", "hoodie", "tops"],
  },
  {
    id: "speed-arm-sleeves",
    name: "Speed Arm Sleeves",
    category: "Accessories",
    price: 42,
    availability: "In stock",
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=800&fit=crop",
    ],
    description: "UV-protected performance arm sleeves for runners and cyclists. Lightweight and comfortable with compression for better circulation.",
    features: ["UPF 50+ UV protection", "Graduated compression", "Moisture-wicking fabric", "Seamless flat construction", "Silicone grip top and bottom"],
    variants: [
      { size: "S/M", color: "Black", stock: 20 },
      { size: "L/XL", color: "Black", stock: 15 },
      { size: "S/M", color: "White", stock: 12 },
      { size: "L/XL", color: "White", stock: 8 },
    ],
    reviews: [
      { id: "r14", author: "Chris N.", rating: 4, date: "2024-10-25", title: "Great UV protection", body: "These stayed in place throughout my 3-hour ride.", verified: true },
    ],
    rating: 4.3,
    reviewCount: 67,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    brand: "Adidas",
    sku: "GMG-SA-008",
    tags: ["accessories", "sleeves"],
  },
  {
    id: "apex-sports-bra",
    name: "Apex Sports Bra",
    category: "Training",
    price: 72,
    availability: "In stock",
    imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=800&fit=crop",
    ],
    description: "High-impact support meets premium comfort. Designed for high-intensity training with maximum support and minimal bounce.",
    features: ["High-impact support", "Removable molded cups", "Racerback design", "Wide supportive straps", "Moisture-wicking inner lining"],
    variants: makeVariants(["XS", "S", "M", "L", "XL"], ["Black", "Navy", "Charcoal"]),
    reviews: [
      { id: "r15", author: "Maria G.", rating: 5, date: "2024-11-08", title: "Finally a sports bra that actually supports", body: "I have a hard time finding sports bras that work for high impact. This is the one.", verified: true },
    ],
    rating: 4.8,
    reviewCount: 156,
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    brand: "Under Armour",
    sku: "GMG-AB-009",
    tags: ["training", "sports-bra", "women"],
  },
  {
    id: "velocity-windbreaker",
    name: "Velocity Windbreaker",
    category: "Running",
    price: 119,
    compareAtPrice: 149,
    availability: "In stock",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=800&h=800&fit=crop",
    ],
    description: "Ultra-lightweight windbreaker designed for speed. Weighs under 100g and packs into its own pocket.",
    features: ["Under 100g total weight", "Wind and water resistant", "Packs into own chest pocket", "Laser-cut ventilation", "360° reflectivity"],
    variants: makeVariants(SIZES, ["Black", "Red", "Blue"]),
    reviews: [
      { id: "r16", author: "Ben A.", rating: 5, date: "2024-10-30", title: "Barely know it's there", body: "The lightest running jacket I've ever used. Packs tiny and keeps the wind off perfectly.", verified: true },
    ],
    rating: 4.6,
    reviewCount: 92,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    brand: "Nike",
    sku: "GMG-VW-010",
    tags: ["running", "jacket", "lightweight"],
  },
  {
    id: "power-training-top",
    name: "Power Training Top",
    category: "Training",
    price: 58,
    availability: "In stock",
    imageUrl: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop",
    ],
    description: "Built for the weight room. Features reinforced stitching, strategic stretch panels, and premium moisture management.",
    features: ["Reinforced seam construction", "Strategic stretch panels", "Flatlock stitching", "Anti-odor treatment", "Slim athletic fit"],
    variants: makeVariants(SIZES, COLORS_TRAINING),
    reviews: [
      { id: "r17", author: "Dave K.", rating: 4, date: "2024-11-14", title: "Solid training top", body: "Great quality and fit. The stretch panels make a real difference.", verified: true },
    ],
    rating: 4.4,
    reviewCount: 88,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    brand: "Puma",
    sku: "GMG-PT-011",
    tags: ["training", "tops", "gym"],
  },
  {
    id: "lifestyle-shorts",
    name: "Lifestyle Training Shorts",
    category: "Lifestyle",
    price: 48,
    availability: "Low stock",
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=800&fit=crop",
    ],
    description: "Versatile shorts for training, running, or everyday wear. Clean minimalist design with performance fabric.",
    features: ["5-inch inseam", "Side zip pocket", "Lightweight woven fabric", "Internal brief liner", "Quick-dry technology"],
    variants: makeVariants(["S", "M", "L", "XL", "XXL"], COLORS_BASIC),
    reviews: [
      { id: "r18", author: "Finn O.", rating: 5, date: "2024-09-28", title: "My new everyday shorts", body: "I wear these for everything — gym, running, casual. They look great and perform even better.", verified: true },
    ],
    rating: 4.5,
    reviewCount: 134,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    brand: "New Balance",
    sku: "GMG-CS-012",
    tags: ["lifestyle", "shorts", "versatile"],
  },
];

export const categories = [
  {
    id: "Running",
    name: "Running",
    nameAr: "الجري",
    description: "Speed. Endurance. Victory.",
    count: products.filter((p) => p.category === "Running").length,
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=800&fit=crop",
  },
  {
    id: "Football",
    name: "Football",
    nameAr: "كرة القدم",
    description: "Play like a champion.",
    count: products.filter((p) => p.category === "Football").length,
    imageUrl: "https://images.unsplash.com/photo-1511886929837-354d827aae26?w=600&h=800&fit=crop",
  },
  {
    id: "Training",
    name: "Training",
    nameAr: "التدريب",
    description: "Strength. Power. Dominance.",
    count: products.filter((p) => p.category === "Training").length,
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=800&fit=crop",
  },
  {
    id: "Basketball",
    name: "Basketball",
    nameAr: "كرة السلة",
    description: "Rise above the competition.",
    count: products.filter((p) => p.category === "Basketball").length,
    imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&h=800&fit=crop",
  },
  {
    id: "Lifestyle",
    name: "Lifestyle",
    nameAr: "أسلوب حياة",
    description: "Athletic style for every day.",
    count: products.filter((p) => p.category === "Lifestyle").length,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=800&fit=crop",
  },
  {
    id: "Accessories",
    name: "Accessories",
    nameAr: "الإكسسوارات",
    description: "The details that define you.",
    count: products.filter((p) => p.category === "Accessories").length,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=800&fit=crop",
  },
];

export const brands = [
  { id: "nike", name: "Nike", displayName: "NIKE" },
  { id: "adidas", name: "Adidas", displayName: "adidas" },
  { id: "puma", name: "Puma", displayName: "PUMA" },
  { id: "under-armour", name: "Under Armour", displayName: "UNDER ARMOUR" },
  { id: "new-balance", name: "New Balance", displayName: "New Balance" },
  { id: "asics", name: "Asics", displayName: "ASICS" },
];
